export const env = {
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL || "",
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "",
  AFTERSHIP_API_KEY: process.env.AFTERSHIP_API_KEY || "",
  RESEND_API_KEY: process.env.RESEND_API_KEY || "",
};
